pipeline {
    agent none

    stages {

        stage('Compile on Agent 1') {
            agent { label 'agent1' }
            steps {
                checkout scm

                dir('23070122265_MithleshYadav/Project_4_Distributed_Jenkins_Maven/portfolio') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test on Agent 2') {
            agent { label 'agent2' }
            steps {
                checkout scm

                dir('23070122265_MithleshYadav/Project_4_Distributed_Jenkins_Maven/portfolio') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package on Agent 2') {
            agent { label 'agent2' }
            steps {
                dir('23070122265_MithleshYadav/Project_4_Distributed_Jenkins_Maven/portfolio') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Distributed Maven pipeline completed successfully.'
        }

        failure {
            echo 'Distributed Maven pipeline failed.'
        }
    }
}